In [45]:
import pandas as pd 
df=pd.read_csv('updated_dataset_after_task_1.csv')

In [46]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [47]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
# Calculate mean of 'TotalCharges' excluding NaN values
mean_total_charges = df['TotalCharges'].mean()

# Fill NaN values in 'TotalCharges' with its mean
df['TotalCharges'].fillna(mean_total_charges, inplace=True)

In [48]:
bool_cols = df.select_dtypes(include=['bool']).columns
bool_cols

Index(['gender_Female', 'gender_Male', 'Partner_No', 'Partner_Yes',
       'Dependents_No', 'Dependents_Yes', 'PhoneService_No',
       'PhoneService_Yes', 'MultipleLines_No',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'OnlineSecurity_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No', 'OnlineBackup_No internet service',
       'OnlineBackup_Yes', 'DeviceProtection_No',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No', 'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No', 'StreamingMovies_No internet service',
       'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaperlessBilling_No', 'PaperlessBilling_Yes',
       'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check',
       'Churn_No', 'Churn_Yes'],
      dtype='object')

In [49]:
#converting all bool values to integer 
for col in bool_cols:
    df[col]=df[col].apply(lambda x: 1 if x == True else 0)

In [50]:
x=df.drop(columns=['Churn_Yes', 'Churn_No', 'customerID'])
y = df['Churn_Yes'].apply(lambda x: 1 if x == True else 0)

Identify key factors influencing churn and Propose data-driven strategies to reduce churn.suggest actions.

In [52]:



# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Build RandomForest model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Get feature importances
feature_importances = model.feature_importances_
features = x.columns
importance_df = pd.DataFrame({'Feature': features, 'Importance': feature_importances}).sort_values(by='Importance', ascending=False)
print(importance_df)

                                    Feature  Importance
3                              TotalCharges    0.157925
2                            MonthlyCharges    0.138368
1                                    tenure    0.135567
36                  Contract_Month-to-month    0.055016
43           PaymentMethod_Electronic check    0.033790
18                        OnlineSecurity_No    0.028794
27                           TechSupport_No    0.026018
16              InternetService_Fiber optic    0.023482
0                             SeniorCitizen    0.020193
21                          OnlineBackup_No    0.019668
38                        Contract_Two year    0.018680
4                             gender_Female    0.018337
5                               gender_Male    0.017533
39                      PaperlessBilling_No    0.016113
24                      DeviceProtection_No    0.015463
6                                Partner_No    0.015177
7                               Partner_Yes    0.014855
40                     PaperlessBilling_Yes    0.014763
12                         MultipleLines_No    0.013660
14                        MultipleLines_Yes    0.013655
20                       OnlineSecurity_Yes    0.012885
8                             Dependents_No    0.012802
35                      StreamingMovies_Yes    0.012358
41  PaymentMethod_Bank transfer (automatic)    0.012355
29                          TechSupport_Yes    0.011996
42    PaymentMethod_Credit card (automatic)    0.011987
37                        Contract_One year    0.011861
9                            Dependents_Yes    0.011828
23                         OnlineBackup_Yes    0.011723
44               PaymentMethod_Mailed check    0.011618
32                          StreamingTV_Yes    0.011521
26                     DeviceProtection_Yes    0.011475
15                      InternetService_DSL    0.011113
30                           StreamingTV_No    0.011070
33                       StreamingMovies_No    0.010712
31          StreamingTV_No internet service    0.004053
34      StreamingMovies_No internet service    0.003231
10                          PhoneService_No    0.003140
13           MultipleLines_No phone service    0.003094
11                         PhoneService_Yes    0.002980
19       OnlineSecurity_No internet service    0.002453
22         OnlineBackup_No internet service    0.002043
17                       InternetService_No    0.001683
25     DeviceProtection_No internet service    0.001560
28          TechSupport_No internet service    0.001402

In [53]:
x.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Female', 'gender_Male', 'Partner_No', 'Partner_Yes',
       'Dependents_No', 'Dependents_Yes', 'PhoneService_No',
       'PhoneService_Yes', 'MultipleLines_No',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'OnlineSecurity_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No', 'OnlineBackup_No internet service',
       'OnlineBackup_Yes', 'DeviceProtection_No',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No', 'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No', 'StreamingMovies_No internet service',
       'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaperlessBilling_No', 'PaperlessBilling_Yes',
       'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

Calculate the lifetime value (LTV) of customers.

In [54]:
# Calculate ARPU (using MonthlyCharges as an estimate)
#Average Revenue per Customer (ARPU)
arpu = df['TotalCharges'].mean()

# Calculate Average Lifespan (using tenure)
average_lifespan = df['tenure'].mean()

# Calculate LTV(life time value)
#Lifetime Value or LTV is an estimate of the average revenue that a customer will generate throughout their lifespan as a customer.
# we can call ltv as clv(customer lifetime value)
ltv = arpu * average_lifespan

In [58]:
print("Lifetime Value or LTV: ",ltv)

Lifetime Value or LTV:  73913.05800192204

In [59]:
df

,customerID,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,...,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_No,Churn_Yes
0,7590-VHVEG,0,1,29.85,29.85,1,0,0,1,1,...,0,0,0,1,0,0,1,0,1,0
1,5575-GNVDE,0,34,56.95,1889.50,0,1,1,0,1,...,1,0,1,0,0,0,0,1,1,0
2,3668-QPYBK,0,2,53.85,108.15,0,1,1,0,1,...,0,0,0,1,0,0,0,1,0,1
3,7795-CFOCW,0,45,42.30,1840.75,0,1,1,0,1,...,1,0,1,0,1,0,0,0,1,0
4,9237-HQITU,0,2,70.70,151.65,1,0,1,0,1,...,0,0,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,24,84.80,1990.50,0,1,0,1,0,...,1,0,0,1,0,0,0,1,1,0
7039,2234-XADUH,0,72,103.20,7362.90,1,0,0,1,0,...,1,0,0,1,0,1,0,0,1,0
7040,4801-JZAZL,0,11,29.60,346.45,1,0,0,1,0,...,0,0,0,1,0,0,1,0,1,0
7041,8361-LTMKD,1,4,74.40,306.60,0,1,0,1,1,...,0,0,0,1,0,0,0,1,0,1
7042,3186-AJIEK,0,66,105.65,6844.50,0,1,1,0,1,...,0,1,0,1,1,0,0,0,1,0

In [60]:
df['Churn']=df['Churn_Yes'].apply(lambda x:1 if x else 0)

In [64]:
df.drop(columns=['Churn_Yes','Churn_No'])

,customerID,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,...,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn
0,7590-VHVEG,0,1,29.85,29.85,1,0,0,1,1,...,1,0,0,0,1,0,0,1,0,0
1,5575-GNVDE,0,34,56.95,1889.50,0,1,1,0,1,...,0,1,0,1,0,0,0,0,1,0
2,3668-QPYBK,0,2,53.85,108.15,0,1,1,0,1,...,1,0,0,0,1,0,0,0,1,1
3,7795-CFOCW,0,45,42.30,1840.75,0,1,1,0,1,...,0,1,0,1,0,1,0,0,0,0
4,9237-HQITU,0,2,70.70,151.65,1,0,1,0,1,...,1,0,0,0,1,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,24,84.80,1990.50,0,1,0,1,0,...,0,1,0,0,1,0,0,0,1,0
7039,2234-XADUH,0,72,103.20,7362.90,1,0,0,1,0,...,0,1,0,0,1,0,1,0,0,0
7040,4801-JZAZL,0,11,29.60,346.45,1,0,0,1,0,...,1,0,0,0,1,0,0,1,0,0
7041,8361-LTMKD,1,4,74.40,306.60,0,1,0,1,1,...,1,0,0,0,1,0,0,0,1,1
7042,3186-AJIEK,0,66,105.65,6844.50,0,1,1,0,1,...,0,0,1,0,1,1,0,0,0,0

In [66]:
df.to_csv('final_dataset.csv',index=False)

In [69]:
df.columns

Index(['customerID', 'SeniorCitizen', 'tenure', 'MonthlyCharges',
       'TotalCharges', 'gender_Female', 'gender_Male', 'Partner_No',
       'Partner_Yes', 'Dependents_No', 'Dependents_Yes', 'PhoneService_No',
       'PhoneService_Yes', 'MultipleLines_No',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'OnlineSecurity_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No', 'OnlineBackup_No internet service',
       'OnlineBackup_Yes', 'DeviceProtection_No',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No', 'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No', 'StreamingMovies_No internet service',
       'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaperlessBilling_No', 'PaperlessBilling_Yes',
       'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check',
       'Churn_No', 'Churn_Yes', 'Churn'],
      dtype='object')